"use client";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useUser } from "@clerk/nextjs";
import MainLoader from "@/components/MainLoader";

const sections = [
  {
    id: 1,
    title: "1. Platform Usage",
    content:
      "CourseFlow provides AI-assisted tools to create, manage, and explore structured learning paths and educational content. You agree to use the platform responsibly, lawfully, and in a way that does not disrupt the service or harm other users.",
  },
  {
    id: 2,
    title: "2. User Accounts & Security",
    content:
      "You are responsible for maintaining the confidentiality of your account credentials and all activities performed under your account. CourseFlow is not liable for any loss or damage arising from unauthorized access caused by your failure to protect your account.",
  },
  {
    id: 3,
    title: "3. Content & Ownership",
    content:
      "All content created, uploaded, or generated by users remains the responsibility of the respective user. CourseFlow does not guarantee the accuracy, reliability, or educational value of AI-generated or user-generated content.",
  },
  {
    id: 4,
    title: "4. Service Availability & Termination",
    content:
      "We reserve the right to modify, suspend, or terminate access to the platform at any time, with or without notice, if a user violates these terms or engages in abusive, harmful, or unlawful behavior.",
  },
  {
    id: 5,
    title: "5. Changes to These Terms",
    content:
      "CourseFlow may update these Terms and Conditions from time to time. Continued use of the platform after changes are made constitutes acceptance of the revised terms.",
  },
  {
    id: 6,
    title: "6. Contact & Support",
    content:
      "If you have any questions, concerns, or feedback regarding these Terms and Conditions, please contact us through the platform or our official communication channels.",
  },
];

const TermsPage = () => {
  const { isSignedIn, isLoaded } = useUser();
  if (!isLoaded)
    return (
      <div
        style={{
          position: "fixed",
          inset: 0,
          display: "grid",
          placeItems: "center",
          backgroundColor: "#ffffff",
          zIndex: 9999,
        }}
      >
        <MainLoader />
      </div>
    );

  return (
    <>
      <Header
        text={isSignedIn ? "Dashboard" : "Home"}
        link={isSignedIn ? "dashboard" : ""}
        fallback={isSignedIn ? "dashboard" : ""}
      />

      <div className="min-h-screen bg-white pt-16 sm:pt-20">
        <div className="max-w-[680px] sm:max-w-screen-2xl mx-auto px-7 sm:px-6 py-10 sm:py-16">
          <div className="mb-8 sm:mb-14 text-center sm:text-left">
            <h1 className="text-xl sm:text-3xl font-semibold text-slate-900 mb-1">
              Terms & Conditions
            </h1>
            <p className="text-xs sm:text-sm text-slate-500">
              Last updated: 15/01/2026
            </p>
          </div>

          <p className="text-center sm:text-left text-sm sm:text-lg text-slate-600 leading-relaxed mb-10 sm:mb-16">
            Welcome to{" "}
            <span className="font-semibold text-[#155DFC]">
              Course<span className="italic">Flow</span>
            </span>
            . By using our platform, you agree to the terms outlined below.
            We’ve kept them as clear and straightforward as possible.
          </p>

          <div className="space-y-10 sm:space-y-16">
            {sections.map((section) => (
              <section key={section.id}>
                <div className="flex items-start gap-3 mb-3">
                  <span className="w-6 h-6 shrink-0 flex items-center justify-center bg-blue-50 text-[#155DFC] rounded-md text-xs sm:text-sm mt-0.5">
                    {section.id}
                  </span>
                  <h2 className="text-base sm:text-xl font-semibold text-slate-900 leading-snug">
                    {section.title.split(". ")[1]}
                  </h2>
                </div>

                <p className="text-sm sm:text-base text-slate-600 leading-relaxed sm:pl-9">
                  {section.content}
                </p>
              </section>
            ))}
          </div>
        </div>

        <Footer />
      </div>
    </>
  );
};

export default TermsPage;
